### ISSUE TITLE
I want to join the pilot if possible

### ISSUE THREAD

**Issue by JohanvanZanten** [athombv/com.nest#1]
Like stated in the title

**Comment by RobinBol** [comment]
We are working on preparing the app for this pilot, we expect to have it up coming week. Unfortunately I don't have any say on who gets to participate, its a first come first serve mechanism, however I will shoot you a message as soon as it is up!

**Comment by filoor** [comment]
do you know if the gone make it this week

**Comment by RobinBol** [comment]
Hi guys, as promised; the nest app will hit the app store today!
