### ISSUE TITLE
feature request: Set away status with homey

### ISSUE THREAD

**Issue by dkruyt** [athombv/com.nest#10]
Please add that you can set the away status with homey.

**Comment by RobinBol** [comment]
In a flow this will never be possible due to Nest's policy, I quote: 

> Home and Away are set via user interaction in the Nest app or on the Nest Thermostat. Products that set Home or Away must prompt and require a user confirmation for each Home/Away transition.

**Comment by dkruyt** [comment]
Ah, to bad, want to use it to make a poormans alarm system with nest a motion detection... I have it already in place but wanted more control...

Thanks for your reply
