### ISSUE TITLE
not working jet

### ISSUE THREAD

**Issue by filoor** [athombv/com.nest#2]
I just put it on my homey to gif it a try but after install and ik i want to add a device it stocks

![1](https://cloud.githubusercontent.com/assets/3647638/13116937/33a0adaa-d59e-11e5-89e6-3a9e585fbce0.jpg)

**Comment by RobinBol** [comment]
That is not going to work, you have to wait for the app to be released on the app store!

**Comment by filoor** [comment]
Oke
