### ISSUE TITLE
Setting temperature using variable (feature request)

### ISSUE THREAD

**Issue by Vortjong** [athombv/com.nest#20]
Hi,

thanks for the great app! I have one question :

Currently is the temperature is set using a slider, which sets the exact temperature. I would like to make flow which sets the temperature based on a variable. Is this possible ?

**Comment by RobinBol** [comment]
Hi, 

Thanks for your idea! Unfortunately, the Nest app uses generic thermostat flow cards, so I can not change this for you. If you wish, you can create an issue [here](https://github.com/athombv/homey/issues), then Emile can take a look at your suggestion.
