### ISSUE TITLE
No status after reboot in Nest Protect Card

### ISSUE THREAD

**Issue by StraDijk** [athombv/com.nest#22]
There is no status in the card when you reboot the Homey.

Re-adding the device(s) solves the problem until the next reboot.

![2016-10-04 13_41_08- 1 homey zones devices](https://cloud.githubusercontent.com/assets/2519741/19072911/40b855fc-8a38-11e6-881f-23c4b93e3434.png)

**Comment by RobinBol** [comment]
Thanks for reporting, this appears to be a generic issue for which I created an issue over here https://github.com/athombv/homey/issues/961

**Comment by RobinBol** [comment]
It appeared to be an app specific issue. This will be fixed in the next major release of the Nest app.

**Comment by RobinBol** [comment]
This issue should be fixed by now, if I am wrong and it still exists please let me know by re-opening this issue.
