### ISSUE TITLE
Empty follow instructions Window

### ISSUE THREAD

**Issue by rodebeer** [athombv/com.nest#23]
I just received my new homey and tries to add a Nest thermostat to my devices. The "follow the instructions" window is blank.
![nest_issue](https://cloud.githubusercontent.com/assets/5113657/19160999/63ab053a-8bf2-11e6-871a-1e10321e268f.png)

Under settings I tried to approve Athom to use my Nest products. I end up in the oauth window of Nest and can approve, but the small radar for setting the approval state keeps on spinning. So it seems it does not receive or can process the request.

I am running Homey Firmware Version: 0.10.3

**Comment by RobinBol** [comment]
Thanks for reporting, try disabling/enabling the app and then again try to pair (perhaps a few times necessary), caused by limited number of clients supported by Nest at the moment.

**Comment by rodebeer** [comment]
I had to reinstall the app from the app center, then it fixed the issue.
