### ISSUE TITLE
 Set Away

### ISSUE THREAD

**Issue by dnhaas** [athombv/com.nest#27]
would be nice to have a card to set or un-set the away function of the nest

**Comment by RobinBol** [comment]
Sorry, not allowed by Nest API policy!

**Comment by dnhaas** [comment]
does nest also have a github haha....

**Comment by lucasvdh** [comment]
@RobinBol is it still the case that this is not providedby the API? Because it looks like it is nowadays.

References:
- https://developers.nest.com/reference/api-structure#away (has read/write)
- https://developers.nest.com/guides/api/how-to-write-data

Example request setting the away status:
```
curl --location-trusted -X PUT \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer YOUR_TOKEN_HERE" \
  -d '{"away": "home"}' \
  "https://developer-api.nest.com/structures/structure_id"
```

**Comment by RobinBol** [comment]
FYI, using the latest Nest app it is possible to adjust the target temperature even when your structure is in away mode. Setting the away mode through Homey is as of yet not implemented.
