### ISSUE TITLE
can not add nest devices

### ISSUE THREAD

**Issue by satbopper** [athombv/com.nest#28]
i gave nest permission to work with homey
on my tel app,i can see that the permission for homey is available
if i try to add the nest thermostat or nest protect i get the message "er zijn geen nieuwe apparaten gevonden"
rebooted homey  then same issue
ptp then same issue
there is a normal wifi connection from the nest thermostat to my router,with my tel app i can work with it as normal

**Comment by maartentamboer** [comment]
I have the same issue.
Homey Nest app: v2.2.1
Homey Firmware Versie: 1.1.2
Using the homey app on OSX

To reproduce
Install nest app
Settings -> Nest -> Authenticate -> chrome opens with nest website
After I authenticate on the nest website it goes to a blank page at callback.athom.com
The gear icon at settings -> nest stays spinning

When I look at the Nest app at Works with Nest I can see Athom Homey. But "Laatst gebruikt" contains "-" meaning that the connection was never used

**Comment by satbopper** [comment]
is there any progress on above situation by Athom ??????

**Comment by RobinBol** [comment]
The problem is, I have tried many times but can not reproduce your issue. My guess is the Nest API is not always that responsive, or somehow gets blocked; got a user who reported an error on the settings page of the Nest app saying his connection was temporarily blocked due to rate limits, could you let me know if you have the same error in the Nest app settings page or not?

**Comment by maartentamboer** [comment]
I don't see any error on the settings page. Just the spinning gear icon.

![capture](https://cloud.githubusercontent.com/assets/1395437/22020436/8f830f88-dcb8-11e6-838e-f73e9ba90fe7.PNG)

**Comment by RobinBol** [comment]
Ok, and if you now try to add a Nest device (you should not have to authenticate again), it say "no new devices found"?

**Comment by maartentamboer** [comment]
Yes

**Comment by maartentamboer** [comment]
![nest](https://cloud.githubusercontent.com/assets/1395437/22020776/515dbdaa-dcba-11e6-87fc-59d6e22a551d.PNG)
![nieuwe_apparaten](https://cloud.githubusercontent.com/assets/1395437/22020779/52e4cf6a-dcba-11e6-919c-88f1ddfb507c.PNG)

**Comment by maartentamboer** [comment]
![last_use](https://cloud.githubusercontent.com/assets/1395437/22020894/d255a634-dcba-11e6-9c42-b00477f74c34.PNG)

**Comment by maartentamboer** [comment]
To make the steps to reproduce it a bit more clear I've created a short screen capture:
https://youtu.be/A0puJ-9nCIQ

**Comment by RobinBol** [comment]
Thank you for the extensive information, we'll dive into it.

**Comment by satbopper** [comment]
ok thanks maartentamboer for the supplied info,all i can say i have totally the same issue and i think it started for me after a suddenly lost of wifi of homey,router and the internet
i made on the nest website an extra family member,then for me it is possible to make the permission in homey en (trek permission terug},there is also a message that only the owner of the nest can give permission,strange if i login with the owner of the nest,in homey there is a constant spinning wheel and on the nest owner account there is a permission available
then if you close the nest app and start again the both devices for me are endless spinning
the strange thing is that the last week that i got installed the nest,it worked with homey
my guess is that the devices are in some way already available but you can not see them in homey

**Comment by maartentamboer** [comment]
I've had my homey since Sunday, and immediately had the issue.

**Comment by satbopper** [comment]
yes there is something happened,i removed the nest app and again installed it,left it for an hour
then i did through the devices a permission and they are added,maybe i am raaskalling hi but the both devices are now added
maartentamboer have a try

**Comment by satbopper** [comment]
@RobinBol or me the nest is working now,but there is one issue the luchtvochtigheid in not updated in the flow tags,temp and selected temp is ok

**Comment by RobinBol** [comment]
Hi guys, got some info from Nest:
1. They experienced some issues with the API past month.
2. Devices that are recently added to a Nest account can take up to 30 minutes to be accessible by the API, this might be the cause for most of the people not finding their devices in Homey.

@maartentamboer could you try reinstall the Nest app and add the devices? I am curious whether your problem is solved by now are still existing.

**Comment by maartentamboer** [comment]
I've tried it. And its working now, I authenticate and the thermostat shows up.
Thanks :+1:

**Comment by RobinBol** [comment]
Great, thanks for the help guys!
