### ISSUE TITLE
Homey can't set temperature if away status is away

### ISSUE THREAD

**Issue by WrDX** [athombv/com.nest#30]
I'm trying to create a flow where Homey asks me to turn on the heater through Nest. I'm not at home and for that reason Homey can't set the temperature:

```Kon doeltemperatuur niet aanpassen naar 19.5 terwijl structure op away modus stond ingesteld```

If I try it with the Nest app, I get the message that I need to disable eco, and then I can change the temperature in the Nest app. But even If I set the Nest to heating, Homey still can't change the temperature.

I would like Homey to be able to change the temperature especially when I'm not home, is this possible?

**Comment by RobinBol** [comment]
You can not do so when the structure has the away state (Nest policy). The only way is to not use the away state, but let Homey handle your presence. I'd recommend to look at our forums (https://forum.athom.com) and see if someone has a similar set up!
