### ISSUE TITLE
Feature request: Support for Nest's HVAC mode

### ISSUE THREAD

**Issue by Corvo** [athombv/com.nest#31]
Since october 2016 Nest got a new feature called Eco temperatures (see: [this post on the Nest blog](https://nest.com/blog/2016/10/17/say-hello-to-eco-temperatures/) ), starting firmware `5.6`.

This feature is currently not supported by the Homey Nest app.
When looking in the [Nest API docs](https://developers.nest.com/documentation/api-reference), I'd think that the following should be possible to implement:

- Device control
_(when using Homey mobile app or when using Homey's web GUI and going to devices)_
Currently the non-ECO mode's temperature is shown, even when the thermostat is set to Eco.
When reading the API and the `hvac_mode` is  `eco` then no temperature should be shown (and not be set).
According to the [docs](https://developers.nest.com/documentation/cloud/thermostat-guide#target-temperature) _"when Eco mode (eco) is selected, the target temperature range is internally set"_ and can thus not be read using the API. I'd think simply displaying "Eco" would suffice, I guess. An alternative could be to show a selector (picker) for the modes?
- HVAC flowcards **(implemented and available since version 2.30)**
Currently the HVAC flowcards only support **state** trigger and condition flowcards. These, indeed, can only be "heating", "cooling" or "off". (and thus, these flowcards work fine) However I'd also like flowcards which support **mode** trigger and condition flowcards. That way other devices can react to the new "Eco" HVAC mode.

Having Eco temperature/mode supported this way, would help immensely.

----

Icing on the cake however would be to using Device control and/or Flowcards to change the `hvac_mode`.
According to the API docs the `hvac_mode` is read/write, so should be possible.

**Comment by Corvo** [comment]
I created a [fork](https://github.com/Twire-Solutions/com.nest/tree/hvac-mode) in which I started development on this.

Status so far:
- `previous_hvac_mode` is only for older firmware and since I can't see a use-case for it either: I decided **not** to implement it.
- Currently the flow trigger, condition and action card for `hvac_mode` is implemented and confirmed to work.
- _TO-DO:_ A device capability which allows to set a `hvac_mode` needs to be done.

@RobinBol Is it possible to use the Nest Thermostat's properties `can_heat`  and `can_cool` to limit the amount of options presented in the dropdown regarding any of the `hvac_mode` flowcards?
(Although unsupported modes are prevented from being set, I'd rather prevent them from being an option to begin with)

**Comment by RobinBol** [comment]
Great work so far! I've added some general comments to your code. Regarding the dropdown, unfortunately we can not dynamically edit the options of the dropdown. So you'll have to present all options unfortunately..

**Comment by Corvo** [comment]
For now I'll just do my best to get HVAC mode support in.

@RobinBol For in some (distant future) update: would it be an idea to define multiple type of "thermostats"? One which Heats, one which Cools and one which Heats+Cools? During thermostat pairing you can read the capabilities and then select the correct "internal type". You would end-up with some duplication in the `app.json`, but the code itself from the driver could remain as-is: the definitions in `app.json`  would simply limit the dropdowns correctly to show only supported hvac mode options.

**Comment by Corvo** [comment]
@RobinBol I created a [pull request](https://github.com/athombv/com.nest/pull/32/files) for HVAC mode support in flows.
Just comment on the pull-request if I need to make any changes or corrections.

_I can confirm all three cards to work correctly (and the action validates the desired mode correctly too)._

**Comment by RobinBol** [comment]
App was updated! If you consider this issue fixed, you may close the issue, or keep it open (and rename it) for the mobile card functionality in the future.

**Comment by Corvo** [comment]
At the moment, the mobile-card isn't a priority for me. _(closing the issue)_
