### ISSUE TITLE
No information in statistics (inzicht)

### ISSUE THREAD

**Issue by j0o5t** [athombv/com.nest#35]
Nest thermostat sensors are not visible in statistics (inzicht). This would be a great help for setting the right tresholds for moisture for instance.

Would it be possible to add this to the plugin?

**Comment by RobinBol** [comment]
No, Nest doesn't allow us to store that data longer than 10 days (which is required by Insights).

**Comment by j0o5t** [comment]
Okay, is it possible in some other way, like through a virtual device, or wil we still be incompliant with the Nest guidelines?

**Comment by RobinBol** [comment]
Nope sorry..

**Comment by j0o5t** [comment]
Ok thanks for your reply! Appreciate it.
