### ISSUE TITLE
Humidity does not get updated

### ISSUE THREAD

**Issue by Tim-Brass** [athombv/com.nest#36]
Looks like Humidity does not get updated in the Homey app.

**Comment by RobinBol** [comment]
Is does over here. Can you provide some more information when creating these issues? Homey version, app version, what are you trying to achieve, what does not work, etc.?

For example, do you mean the Homey Desktop app or Homey Smartphone app?

**Comment by Tim-Brass** [comment]
Hi Robin, 

I did not see it correctly. Looks like the humidity does not report with increments of 1% instead it's increments of 5% (Smartphone app). So 51% humidity is 50% in smartphone app.

**Comment by RobinBol** [comment]
It indeed reports changes of 5% or more, that is a limitation of the API. Thanks for reporting!
