### ISSUE TITLE
Wrong tag in Homey web-app (set temp changed)

### ISSUE THREAD

**Issue by Tim-Brass** [athombv/com.nest#38]
![image](https://user-images.githubusercontent.com/19285656/30855703-2201dbaa-a2b6-11e7-93bc-695c4fe2ce1c.png)

![image](https://user-images.githubusercontent.com/19285656/30855724-34b1e9e8-a2b6-11e7-85a0-53777b99753d.png)
temp tag is attacched to set temp changed card in web-app. Would expect the set temp tag.

**Comment by RobinBol** [comment]
Moved this issue to https://github.com/athombv/homey/issues/2536
