### ISSUE TITLE
Feature request: Create insight data

### ISSUE THREAD

**Issue by rnldnkp** [athombv/com.nest#40]
Not sure if you want me to post this here, but I would like to request a feature.

I was surprised that an App created by Athom does not use the Insights for this Nest app.
Would like to record and compare thermostat data, which currently is only possible by using other apps to detect and save the data (better logic for example).

Could you consider adding insights? There are others who ask the same in de Athom App Store trough comments.

Would like:
- Current temp
- Current Humidity
- Target temp
- HVAC status

**Comment by RobinBol** [comment]
Nest does not allow us to store data for longer than 10 days (which is currently required for Insights): https://github.com/athombv/com.nest/issues/35.
