### ISSUE TITLE
Support for thermostat_mode capability

### ISSUE THREAD

**Issue by nhassink** [athombv/com.nest#42]
Is it possible to add the standard thermostat_mode capability to the nest app?
If so the nest can be controlled from Homekit using the homeykit app.

**Comment by nhassink** [comment]
added it myself and created a PR for this

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2552

**Comment by ChrisBrandhorst** [comment]
@RobinBol I also would like this addition. How is this issue tracked currently? The athombv/homey repo is archived.
