### ISSUE TITLE
Support for Nest Cams on/off (Nest Permissions)

### ISSUE THREAD

**Issue by denniedegroot** [athombv/com.nest#45]
I see that support for Nest Cams already is integrated in the code but I miss the option of turning it on and off. This also requires a different Nest Camera Permission setting (Camera + Images read/write).

I think there are many use cases for this functionality, could you please consider turning this permission on?

**Comment by jeroenvollenbrock** [comment]
This feature is planned for a future Homey version (2.2.0), as it requires Camera Support in Homey first.
