### ISSUE TITLE
Support to set/read Nest Home/Away status with a flow card

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [athombv/com.nest#46]
A flow card to set the Nest Home/Away status.
A flow card to read the Nest Home/Away status.

Reason is to prevent to have multiple apps on my phone which all do location based services with geofence functions.  One app on my phone should be enough to do geofencing.

For example I now use the Tado app for geofencing my house and can set the home/away status of the Homey users using flowcards from the Tado app for Homey.  

Regards, Marco.

**Comment by RobinBol** [comment]
Thanks for your feedback!

Please see: https://github.com/athombv/com.nest/issues/30, https://github.com/athombv/com.nest/issues/27, https://github.com/athombv/com.nest/issues/10 and https://github.com/athombv/com.nest/issues/4.

Reading the Nest away status is already possible in Flows.
