### ISSUE TITLE
Add option to set away status

### ISSUE THREAD

**Issue by lucasvdh** [athombv/com.nest#49]
It would be very usefull to be able to set the away status of a nest structure with a flow card. However good the presence detection of the nest thermostat itself may be, it can always be improved with additional input.

## Why?
For example; when I arrive at home and don't immediately enter the room where my Nest thermostat is located, there can be quite a big delay between when I actually arrive and when Nest recognizes that I'm home.
The presence detection ([BetterPresence](https://github.com/matjaz/homey-better-presence/)) of my Homey would be way faster in this case.

## References
The previous issues #27 and #10, were closed because the API did not allow for this, but is this still the case?

Because it looks like nowadays you can set the away status via the nest API:
- https://developers.nest.com/reference/api-structure#away (has read/write)
- https://developers.nest.com/guides/api/how-to-write-data

Example request setting the away status:
```
curl --location-trusted -X PUT \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer YOUR_TOKEN_HERE" \
  -d '{"away": "home"}' \
  "https://developer-api.nest.com/structures/structure_id"
```

**Comment by ricott** [comment]
This addition would greatly increase the value of this app 👍

**Comment by lucasvdh** [comment]
@RobinBol any update on this? I was thinking I might start on a PR for this feature, but if someone's already working on this feature I'd rather contribute to that rather than start from scratch.

**Comment by RobinBol** [comment]
A PR won't work, we'd need to get our permissions changed before this could be implemented.

**Comment by lucasvdh** [comment]
What permissions are you talking about here, OAuth scopes? Or is there something else I'm overlooking?

**Comment by RobinBol** [comment]
Yes, basically, and in order to get that we need to get our app reviewed by Nest again, so it probably will happen, but on the long term when we have more changed we'd like to make.

**Comment by lucasvdh** [comment]
Why does Nest need to review the app again? On their website (_OAuth Client create page_) they only state:

> **Permissions**
> If you change permissions after the OAuth client is created, then your users will be notified and required to reauthorize the OAuth client with the new permissions.

So it would a nuisance that all users need to reauth.. But personally I'd rather reauth and have some extra features than wait another 6 months before I can get more control over my Nest structures.

If you're planning on requesting more permissions might I also suggest looking into:
- [eta](https://developers.nest.com/reference/api-structure#eta)
- [eta_begin](https://developers.nest.com/reference/api-structure#eta_begin)

**Comment by RobinBol** [comment]
I assumed the permission change required a re-review, maybe we can do without. Since users need te re-auth we want to do this is as little as possible, so when we are going to make additional changes in the future we will look at your request (not the eta stuff though, you can use the Nest app for that if you'd like).

**Comment by lucasvdh** [comment]
Ok, you have any idea when you'll start on those new features? Guess I'll start on my own app in the meantime.

**Comment by RobinBol** [comment]
We can not communicate about timelines unfortunately.

**Comment by RobinBol** [comment]
This feature has been added to the Nest app (beta).

**Comment by lucasvdh** [comment]
Awesome!
