### ISSUE TITLE
Cannot authorize nest with homey

### ISSUE THREAD

**Issue by Vortjong** [athombv/com.nest#5]
Hi,

I have added the homey nest application using the homey store. 
From the homey settings screen, I select Nest and press the button "Authorize Homey to use your nest device".  This results in a new tab, with about:blank in it, nothing more.

My homey is running software version 0.8.20

**Comment by RobinBol** [comment]
That is weird, have you tried authorizing when adding a device?

**Comment by Vortjong** [comment]
No I didn't :-( 
Tried that now, works very smooth. Maybe remove the button from the settings tab ?

**Comment by RobinBol** [comment]
Thanks for your quick response! Weird issue, but I will look into it, for now you can at least add some devices!
