### ISSUE TITLE
Can't be added in FW 2.0.0

### ISSUE THREAD

**Issue by btwvince** [athombv/com.nest#50]
After upgrading a few weeks back to fw 2.0.0 I had to reset my Homey. After that the fw was working but since then I can't get Nest installed on this firmware. 
I can install the app and give permission to Homey but when I want to add the device I need to login again and I can't push the login button. I tried on several devices, tablets, phones and emulators on macbook but nothing is working.

Can this be fixed?

**Comment by RobinBol** [comment]
Thanks for reporting, should be fixed in com.nest@2.5.6 (will be released shortly). Please report if this is not the case.
