### ISSUE TITLE
Ability to read ECO setting / set ECO mode

### ISSUE THREAD

**Issue by Drardollan** [athombv/com.nest#51]
It would be really useful if the app would be able to read the ECO setting and the ability to set it to another setting. ECO mode basically disables the daily schedule and sets it to the ECO temperature. I know this is possible by using the API, I did this on regularly at my previous Domoticz setup.

An example where this is useful: if you want to build a vacation mode flow you could automatically set NEST to ECO mode. When you return from your vacation you could set NEST back to normal mode with another flow.

**Comment by RobinBol** [comment]
Please contact our support department for questions or issues, we are not monitoring these repositories.
