### ISSUE TITLE
Homey to NEST permission is lost

### ISSUE THREAD

**Issue by Drardollan** [athombv/com.nest#52]
Every now and then I see the NEST with a red sign in my Homey. I have to open the app and authenticate my NEST again. It will work a while (not an exact amount of days) and then I need to do it again.

**Comment by RobinBol** [comment]
What does the red sign say?

**Comment by Drardollan** [comment]
I can make a screenshot next time for the exact text, for now I will have to rely on my memory:
On the Devices page it shows the NEST with a red dot in the top right corner, when I click the NEST device it tells me that I have to go to the NEST app and give Homey permission to connect to my NEST account.

**Comment by RobinBol** [comment]
Alright, next time please make a screenshot of the error message and create an app log, you can contact our support team for that. We don't offer support via this issue tracker, so I will close this issue. Thanks for reporting!
