### ISSUE TITLE
Nest Protect Smoke and CO Alarm

### ISSUE THREAD

**Issue by ks2018ks** [athombv/com.nest#56]
Hi I've installed the Nest App https://apps.athom.com/app/com.nest

Added my Nest Protect Smoke and CO Alarm device, but Homey doesn't see to be able to do anything with it.  e.g. when I test the Nest Protect Smoke and CO Alarm, Homey reports nothing.

It shows simple shows a CO and Smoke icon with NO written under each.  What 'support' is the app supposed to give exactly?

**Comment by RobinBol** [comment]
Please contact our support department for questions or issues, we are not monitoring these repositories.
